CREATE TABLE BRANDS (
    BRAND_ID NUMBER PRIMARY KEY,
    BRAND_NAME VARCHAR2(100)
);

CREATE TABLE CATEGORIES (
    CATEGORY_ID NUMBER PRIMARY KEY,
    CATEGORY_NAME VARCHAR2(100)
);

CREATE TABLE PRODUCTS (
    PRODUCT_ID NUMBER PRIMARY KEY,
    PRODUCT_TITLE VARCHAR2(100),
    PRODUCT_DESCRIPTION VARCHAR2(255),
    PRODUCT_KEYWORDS VARCHAR2(100),
    CATEGORY_ID NUMBER,
    BRAND_ID NUMBER,
    PRODUCT_IMAGE1 VARCHAR2(100),
    PRODUCT_IMAGE2 VARCHAR2(100),
    PRODUCT_IMAGE3 VARCHAR2(100),
    DATE_ADDED DATE,
    STATUS BOOLEAN
);
ALTER TABLE PRODUCTS ADD CONSTRAINT FK_PROD_CAT FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES(CATEGORY_ID) ON DELETE SET NULL;
ALTER TABLE PRODUCTS ADD CONSTRAINT FK_PROD_BRN FOREIGN KEY (BRAND_ID) REFERENCES BRANDS(BRAND_ID) ON DELETE SET NULL;

CREATE TABLE ADMIN_TABLE(
    ADMIN_ID NUMBER PRIMARY KEY,
    ADMIN_USERNAME VARCHAR2(100),
    ADMIN_EMAIL VARCHAR2(100),
    ADMIN_PASSWORD VARCHAR2(255),
    ADMIN_IMAGE VARCHAR2(100)
);

CREATE TABLE USER_TABLE(
    USER_ID NUMBER PRIMARY KEY,
    USER_USERNAME VARCHAR2(100),
    USER_EMAIL VARCHAR2(100),
    USER_PASSWORD VARCHAR2(255),
    USER_IMAGE VARCHAR2(100),
    USER_IP VARCHAR2(100),
    USER_ADDRESS VARCHAR2(100),
    USER_MOBILE VARCHAR2(100),
    DISABLED BOOLEAN
);

CREATE TABLE USER_ORDERS (
    ORDER_ID    NUMBER PRIMARY KEY,
    USER_ID NUMBER,
    AMOUNT_DUE NUMBER,
    INVOICE_NUMBER VARCHAR2(100),
    TOTAL_PRODUCTS NUMBER,
    ORDER_DATE DATE,
    ORDER_STATUS VARCHAR2(100)
);
ALTER TABLE USER_ORDERS ADD CONSTRAINT FK_ORD_USR FOREIGN KEY (USER_ID) REFERENCES USER_TABLE(USER_ID);

CREATE TABLE USER_PAYMENTS (
    PAYMENT_ID NUMBER PRIMARY KEY,
    ORDER_ID NUMBER,
    PAYMENT_MOD VARHCAR2(100),
    PAY_DATE DATE
);
ALTER TABLE USER_PAYMENTS ADD CONSTRAINT FK_PAY_ORD FOREIGN KEY (ORDER_ID) REFERENCES USER_ORDERS(ORDER_ID);

CREATE TABLE CART_DETAILS (
    PRODUCT_ID NUMBER,
    IP_ADDRESS VARCHAR2(100),
    USER_ID NUMBER,
    QUANTITY NUMBER,
    PRIMARY KEY (PRODUCT_ID,IP_ADDRESS,USER_ID)
);